apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1 # Commencer à 1 est idéal pour observer l'Autoscaling (HPA) grimper ensuite
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bac-serie-d-backend:latest # ⚙️ Nom d'image local exact corrigé
          imagePullPolicy: IfNotPresent # 🐋 Force l'utilisation de l'image locale Minikube
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
